export const DEFAULT_ENVIRONMENT = 'production';
export const DEFAULT_MAX_BACKENDS_PER_USER = '20';
export const DEFAULT_BACKEND_FETCH_TIMEOUT_MS = '8000';
export const DEFAULT_ROUTE_CACHE_TTL_SECONDS = '86400';
